### ISSUE TITLE
range-slider overview

### ISSUE THREAD

**Issue by nadavwix** [wix/stylable-components#371]
## docs
- [x] is this a range or a multi handle slider?
- [x] what does required means in a slider, is there an empty state?
- [x] remove rtl should be handled by context
- [x] marks and rangeMarks should be implemented as background
- [x] wrong signature for onchange
- [x] tooltip, change to prop and not children with data-slot, needs to be a renderer used  per handle
- [x] change ::handles to ::handle

## edge case handling
- [x] when out of step control should have state invalid/error

**Comment by maksymc** [comment]
1.  "is this a range or a multi handle slider?" -> this is range-slider. I've updated the doc.

2. "what does required means in a slider, is there an empty state?" -> since slider is a form element we preserved "required". This is a default form behavior. If you think that this is a bad idea, we can remove it. 

3. "remove rtl.." -> done

4. "marks and rangeMarks should be implemented as background" -> disagree. This question is being discussed in #353. 

5. "wrong signature for onchange" -> updated the signatures to look like this - http://joxi.ru/Q2KGd36I90aBk2
Let me know that you think. 

6. "change ::handles to ::handle" -> done

7. "tooltip, change to prop and not children with data-slot, needs to be a renderer used per handle" -> will require some additional work

**Comment by nadavwix** [comment]
first 3 are fine
4. i meant if the value changes from outside the slider, and is therefore between steps. 
naturally the slider itself should not allow that

**Comment by maksymc** [comment]
In most cases, this will not happen since the slider is controlling the value. It can occur when (as you said) value changes from the outside and in this case we do not want to set the slider to an error state. It will simply show the wrong step (handle will be a bit out from its expected position) and with next interaction, it will return to its normal state. If you have a case when you need to set a slider to :error, you can do that.

**Comment by maksymc** [comment]
All items are done. Closing.
